### ISSUE TITLE
Rebase on initial GLSP release

### ISSUE THREAD

**Issue by planger** [eclipsesource/ecore-glsp#14]
Once we have a proper release, we should use this released version directly. The progress on the rebase is tracked in https://github.com/eclipsesource/graphical-lsp/issues/123.

**Comment by tortmayr** [comment]
GLSP server modules have been released in version 0.1.0 an can be consumed via maven central repository.
For the client packages, it's not possible to provide a stable release yet because we are heavily depending on nightly (next) sprotty packages. The next offical sprotty release is scheduled for march
