### ISSUE TITLE
Use new layout/align capabilities of GLSP

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/ecore-glsp#75]
E.g. to align two classes

**Comment by planger** [comment]
The `layoutCommandsModule` is defined here: https://github.com/eclipse-glsp/glsp-client/blob/master/src/features/layout/di.config.ts
The registration of the commands in the Theia contribution is here: https://github.com/eclipse-glsp/glsp-theia-integration/blob/master/src/browser/diagram/glsp-diagram-commands.ts
Of course you can also register to invoke those commands via context menu or command palette action, since you just need to invoke the action in GLSP.
